name: AI Stock Server Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy-server-job:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{secrets.APPLICATION_PROPERTIES}}
        with:
          host: ${{ secrets.EC2_HOST }}
          username : ${{ secrets.EC2_USERNAME }}
          key : ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/ai-stock
            rm -rf src/main/resources/application.yml
            git pull origin main
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 80 || true
            nohup java -Duser.timezone=Asia/Seoul -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
            
